name: Build and Push Docker image

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      AWS-REGION: eu-north-1
      EKS_CLUSTER_NAME_PROD: goku-prod-scaling
      ECR_REGISTRY: 975050344723.dkr.ecr.eu-north-1.amazonaws.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: eu-north-1

    - name: Setup repository name
      run: |
        echo "ECR_REPOSITORY=ufo-total-supply" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Build, tag, and push Docker image to Amazon ECR
      run: |
        docker buildx create --use
        docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from=type=s3,mode=max,region=$AWS_REGION,bucket=my-docker-cache-bucket,name=ufototalsupply,compress=true \
          --cache-to=type=s3,mode=max,region=$AWS_REGION,bucket=my-docker-cache-bucket,name=ufototalsupply,compress=true \
          --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --push .

    - name: Verify the image tag
      run: echo "The image tag is $IMAGE_TAG"
    
    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME_PROD --region $AWS_REGION

    - name: Helm setup
      uses: azure/setup-helm@v4.2.0

    - name: Helm add s3 repo
      run: |
        helm plugin install https://github.com/hypnoglow/helm-s3.git
        helm repo add stable-my-static-site s3://vrbl-helm-charts/stable/my-static-site
            
    - name: Update Kubernetes deployment
      env:
        CHART_VERSION: 0.1.8
      run: |
        helm upgrade --install ufo-total-supply stable-my-static-site/my-static-website --version $CHART_VERSION --set image.tag=$IMAGE_TAG --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY --namespace=ufo-total-supply -f helm/values.yaml